spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never
  flyway:
    clean-disabled: true
logging:
  level:
    root: WARN
app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN:https://adam-elzahiri.github.io}
